### ISSUE TITLE
Teste Funcional: Perder o jogo

### ISSUE THREAD

**Issue by remeark** [S2B-2018-Teste/hangman-1#2]

**Comment by MarinhoKraemer** [comment]
[Teste&Feedback.zip](https://github.com/S2B-2018-Teste/hangman-1/files/2380450/Teste.Feedback.zip)

**Comment by remeark** [comment]
[TesteAndFeedbackReport-Kraemer-13-09-2018.html.pdf](https://github.com/S2B-2018-Teste/hangman-1/files/2380452/TesteAndFeedbackReport-Kraemer-13-09-2018.html.pdf)

**Comment by remeark** [comment]
[TesteAndFeedbackReport-Kraemer-13-09-2018.zip](https://github.com/S2B-2018-Teste/hangman-1/files/2380455/TesteAndFeedbackReport-Kraemer-13-09-2018.zip)
